exports.Board = {
    a: {
        1: true,
        2: true,
        3: false,
        4: false,
        5: false,
        6: false,
        7: true,
        8: true,
    },
    b: {
        1: true,
        2: true,
        3: false,
        4: false,
        5: false,
        6: false,
        7: true,
        8: true,
    },
    c: {
        1: true,
        2: true,
        3: false,
        4: false,
        5: false,
        6: false,
        7: true,
        8: true,
    },
    d: {
        1: true,
        2: true,
        3: false,
        4: false,
        5: false,
        6: false,
        7: true,
        8: true,
    },
    e: {
        1: true,
        2: true,
        3: false,
        4: false,
        5: false,
        6: false,
        7: true,
        8: true,
    },
    f: {
        1: true,
        2: true,
        3: false,
        4: false,
        5: false,
        6: false,
        7: true,
        8: true,
    },
    g: {
        1: true,
        2: true,
        3: false,
        4: false,
        5: false,
        6: false,
        7: true,
        8: true,
    },
    h: {
        1: true,
        2: true,
        3: false,
        4: false,
        5: false,
        6: false,
        7: true,
        8: true,
    },
},
function reset() {
    // todo
};
